# Generated by Django 4.1.2 on 2022-10-05 07:00

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Lettres , digits and @/./+/-/ only .', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('user_email', models.EmailField(blank=True, error_messages={'unique': 'A user with that email address  already exists.'}, max_length=254, null=True, unique=True, verbose_name='user email')),
                ('user_password', models.CharField(error_messages={'unique': 'Please password must be between 8-16 characters.'}, help_text='Required 16 maximum characters or minimum 8.', max_length=16, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='user password')),
                ('user_type', models.CharField(choices=[('A', 'Admin'), ('U', 'User'), ('SA', 'Super User')], max_length=10)),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'automation_user',
            },
        ),
    ]
