# Generated by Django 3.1.5 on 2022-10-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20221006_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='username',
            new_name='user_name',
        ),
    ]
